"""Base strategy interface and Signal dataclass."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal, Optional

import pandas as pd


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    figi: str
    ticker: str
    direction: Literal["buy", "sell", "hold"]
    confidence: float  # 0.0 to 1.0
    strategy_name: str
    timestamp: datetime
    suggested_stop_pct: float = 2.0  # Stop distance as % of price
    suggested_target_pct: float = 4.0  # Target as % of price
    features: dict = field(default_factory=dict)
    instrument_kind: Literal["share", "future"] = "share"


@dataclass
class ExitSignal:
    """Signal to exit an existing position."""

    reason: str  # "stop_loss", "take_profit", "signal_reversal", "trailing_stop", "time_exit"
    urgency: Literal["immediate", "next_bar"] = "immediate"


class BaseStrategy(ABC):
    """Abstract base class for trading strategies."""

    name: str = "base"

    @abstractmethod
    async def generate_signal(
        self, figi: str, ticker: str, df: pd.DataFrame, order_book: dict | None = None
    ) -> Signal:
        """Generate a trading signal from market data.

        Args:
            figi: Instrument FIGI.
            ticker: Instrument ticker.
            df: OHLCV DataFrame with indicators.
            order_book: Optional order book data {bids, asks, spread_bps, imbalance}.

        Returns:
            Signal with direction, confidence, and suggested stop/target.
        """
        ...

    @abstractmethod
    async def should_exit(
        self, figi: str, ticker: str, entry_price: float, direction: str, df: pd.DataFrame
    ) -> Optional[ExitSignal]:
        """Check if an open position should be exited.

        Args:
            figi: Instrument FIGI.
            ticker: Instrument ticker.
            entry_price: Position entry price.
            direction: "buy" or "sell".
            df: Current OHLCV DataFrame with indicators.

        Returns:
            ExitSignal if position should be exited, None otherwise.
        """
        ...
